name: ezyfeed
description: "Ezyfeed is a community feed application using Flutter."

dev_app_version: &dev_version 0.0.1+100
prod_app_version: &prod_version 0.0.1+100

version: *dev_version # "*dev_version" or "*prod_version" to be used

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # ui/ux
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2
  flutter_svg: ^2.0.5
  url_launcher: ^6.1.12
  fluttertoast: ^8.2.4
  font_awesome_flutter:

  # state-management
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2

  # dependency-injection
  injectable: ^2.1.0
  get_it: ^8.0.2

  # data-security
  envied: ^0.5.1
  encrypt: ^5.0.1

  # network
  dio: ^5.1.2
  pretty_dio_logger: ^1.3.1

  # data
  drift: ^2.8.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.9
  path: ^1.8.0
  get_storage: ^2.1.1
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  uuid: ^4.0.0
  collection: ^1.17.0
  intl: ^0.19.0
  package_info_plus: ^8.0.2
  device_info_plus: ^11.1.0
  android_id: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code-generation
  drift_dev: ^2.13.0
  injectable_generator: ^2.1.6
  envied_generator: ^0.5.1
  build_runner: ^2.1.4
  json_serializable: ^6.1.4

  # code-quality
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/json/
    - assets/json/forms/
    - assets/icons/
    - assets/icons/at_page/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_thin.ttf
          weight: 100
        - asset: assets/fonts/roboto_thin_italic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/roboto_thin_italic.ttf
          weight: 100
        - asset: assets/fonts/roboto_light.ttf
          weight: 300
        - asset: assets/fonts/roboto_light_italic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/roboto_regular.ttf
          weight: 400
        - asset: assets/fonts/roboto_italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/roboto_medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_medium_italic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_bold_italic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/roboto_black.ttf
          weight: 900
        - asset: assets/fonts/roboto_black_italic.ttf
          style: italic
          weight: 900